namespace System.Diagnostics.Runtime.EventListening.Sources;

/// <summary>
/// Provider name: System.Diagnostics.Eventing.FrameworkEventSource. Provides events generated by
/// the CoreClr libraries.
/// </summary>
/// <see href="https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/FrameworkEventSource.cs"/>
/// <seealso href="https://referencesource.microsoft.com/#mscorlib/system/diagnostics/eventing/frameworkeventsource.cs"/>
public class FrameworkEventSource
{
    // public static readonly Guid Id = Guid.Parse("8e9f5090-2d75-4d03-8a81-e5afbf85daf1");
    public const string Name = "System.Diagnostics.Eventing.FrameworkEventSource";

    [Flags]
    public enum Keywords : long
    {
        Loader = 0x0001,
        ThreadPool = 0x0002,
        NetClient = 0x0004,
        DynamicTypeUsage = 0x0008,
        ThreadTransfer = 0x0010
    }

    public static class EventId
    {
        public const int
            ThreadPoolEnqueueWork = 30,
            ThreadPoolDequeueWork = 31;
    }
}
