namespace System.Diagnostics.Runtime.EventListening.Sources;

/// <summary>
/// Provider name: System.Net.NameResolution. Provides events generated by
/// the CoreClr libraries.
/// </summary>
/// <see href="https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionTelemetry.cs"/>
public class NameResolutionEventSource
{
    public const string Name = "System.Net.NameResolution";
}
