namespace System.Diagnostics.Runtime.EventListening.Sources;

/// <summary>
/// Provider name: System.Net.Sockets. Provides events generated by
/// the CoreClr libraries.
/// </summary>
/// <see href="https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketsTelemetry.cs"/>
public class SocketsEventSource
{
    public static readonly string Name = "System.Net.Sockets";
}
