namespace System.Diagnostics.Runtime.EventListening.Sources;

/// <summary>
/// Provider name: System.Runtime. Provides counters generated by the .NET runtime.
/// </summary>
/// <see href="https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs"/>
public class SystemRuntimeEventSource
{
    // public static readonly Guid Id = new ("49592C0F-5A05-516D-AA4B-A64E02026C89");
    public const string Name = "System.Runtime";
}
